#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cmath>
#include "boost/random.hpp"
#include "boost/random/uniform_real.hpp"
#include "boost/random/variate_generator.hpp"
