#include "gtest/gtest.h"
#include <algorithm>
#include <memory>
#include <vector>
#include <iostream>
#include <fstream>
#include <sstream>
#include <cmath>
#include "boost/random.hpp"
#include "boost/random/uniform_real.hpp"
#include "boost/random/variate_generator.hpp"
